sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
install: npm install
before_script:
  - npm prune
script:
  - npm run test
  - npm run build
branches:
  only:
    - master
    - /^greenkeeper/.*$/
